### ISSUE TITLE
Not work on visual studio 2017/15/13

### ISSUE THREAD

**Issue by jordanmv1c** [gralin/crx14#1]

**Comment by gralin** [comment]
@jordanmv1c any details? This project has been moved from Codeplex as Microsoft is shuting it down. You can find more info about this project here:

http://crx14.codeplex.com/
https://www.ghielectronics.com/community/forum/topic?id=5516

**Comment by jordanmv1c** [comment]
@gralin 
Hi
I not with pc now,but you can download this project and try to open it with visual studio and get error.
Did you wrote this code? Is this code support on windows?
Do i need  to install something before i use this code?

**Comment by gralin** [comment]
@jordanmv1c Yes, this is a .NET Micro Framework project so you need .NET Micro Framework to build it in Visual Studio. You can download it from here:

https://github.com/NETMF/netmf-interpreter/releases
http://netmf.codeplex.com/releases/view/611040

**Comment by userDevop123** [comment]
@gralin Thank about your fast reply.
i install the micro framwork msi.
what should i do now to build it ,and open and run it via visual studio?

**Comment by gralin** [comment]
@userDevop123 I guess you've installed the latest 4.4 version. This project was created long time ago when version 4.1 was the latest one and wasn't upgraded since. Till version 4.3 all previous versions were redistributed with the installer but now I see with version 4.4 you only get this version in your system. Instead of having to install old version of the .net micro framework I have pushed a change to the repo with framework upgrade. So now when you pull it, you will be able to open and build the project from within your Visual Studio 2015 or earlier. Question is, do you have any .net micro framework compatible hardware to test it?

**Comment by userDevop123** [comment]
@gralin firt of all thank you
I install 4.4yes,but it not connect to my visual studio...it like seperate program
So i don't understand how can i open and run it?

**Comment by gralin** [comment]
@userDevop123 on what board are you trying to run this code on?
